--insert into user_details (id, birthdate, name)
--values (10001, current_date(), 'Chandan');
--
--insert into user_details (id, birthdate, name)
--values (10002, current_date(), 'Jaish');
--
--insert into user_details (id, birthdate, name)
--values (10003, current_date(), 'Ujjwal');
--
--insert into user_details (id, birthdate, name)
--values (10004, current_date(), 'Aman');
--
--insert into post (id, description, user_id)
--values (20001, 'I want to earn', 10001);
--
--insert into post (id, description, user_id)
--values (20002, 'I want to live', 10002);
--
--insert into post (id, description, user_id)
--values (20003,'I want to learn', 10003);
